name: Run Crypto Scanner

on:
  schedule:
    # Runs at 5 minutes past every 2nd hour (e.g., 00:05, 02:05, 04:05 UTC)
    # This matches your 3:05, 5:05, 7:05 KSA time scans
    - cron: '5 */2 * * *'
  workflow_dispatch: # Allows you to run it manually from GitHub

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install ccxt pandas
          pip install ccxt # Explicitly install ccxt base

      - name: Run scanner worker
        run: python worker.py

      - name: Commit and push if database changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated scan: Update database"
          file_pattern: 'scanner_data.db'